# Use the gcloud cloud builder (it is a container image running common tools) - analogous to a GL 'runner'?
# This step runs the unit tests on the app
steps:
  - name: 'python:3.7-slim'
    id: Test
    entrypoint: /bin/sh
    args:
    - -c
    - 'pip install -r requirements.txt'

# && python test_app.py -v'
# - name: "gcr.io/cloud-builders/gcloud"
#   id: "AppEngine Deploy"
#   entrypoint: "gcloud"
#   args: ["app", "deploy"]
#   dir: "text_classifier"
#   timeout: "1600s"