# Use the gcloud cloud builder (it is a container image running common tools) - analogous to a GL 'runner'?
steps:
  # This step runs the unit tests on the app
  - name: 'python:3.7-slim'
    id: Test
    entrypoint: /bin/sh
    args:
    - -c
    - 'pip install -r requirements.tst && pytest .'
- name: "gcr.io/cloud-builders/gcloud"
  id: "AppEngine Deploy"
  entrypoint: "gcloud"
  args: ["app", "deploy"]
  dir: "text_classifier"
  timeout: "1600s" 
