steps:
# Use the gcloud cloud builder (it is a container image running common tools) - analogous to a GL 'runner'?
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "gcloud"
  args: ["app", "deploy"]
  timeout: "1600s" 