# Use the gcloud cloud builder (it is a container image running common tools) - analogous to a GL 'runner'?
steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "gcloud"
  args: ["app", "deploy", "text_classifier"]
  timeout: "1600s" 