# runtime: python
# runtime: python37 # Use the provided python environment (don't use the custom Dokcerfile)
runtime: custom # Use the dockerfile provided in the repo
# instance_class: F1 # https://cloud.google.com/appengine/docs/standard#instance_classes
entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8080
# entrypoint: gunicorn -b :$PORT main:app
# env: flex # Somehow clashes with pytho37 environment


runtime_config:
  python_version: 3

# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 0.1
  memory_gb: 0.2
  disk_size_gb: 0.2
